---
- name: Start instances, add to inventory
  hosts: localhost
  connection: local
  tasks:
    - name: Start an instance with a public IP address
      # AWS auth data are stored with awscli
      amazon.aws.ec2_instance:
        name: "ansible-{{ item }}"
        region: us-east-1
        # We have a preexisting key
        key_name: root-01
        instance_type: t2.micro
        # We have a preexisting SG
        security_group: 22-80-8080
        wait: yes
        state: running
        network:
          assign_public_ip: true
        image_id: ami-0261755bbcb8c4a84
        tags:
          ansible: "{{ item }}"
      with_items:
        - build
        - prod

      # Assume that no other hosts with tags "ansible: build/prod" exist
    - name: Get host info
      amazon.aws.ec2_instance_info:
        filters:
          instance-state-name: [ "running" ]
          "tag:ansible": [ "build", "prod" ]
      register: ec2

    - name: Create in-memory inventory for EC2 hosts
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: "{{ item.tags.ansible }}"
        ansible_host: "{{ item.public_ip_address }}"
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /root/.ssh/root-01.pem
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ConnectionAttempts=20"
      with_items: "{{ ec2.instances }}"

- name: Build boxfuse
  hosts: build
  become: yes
  become_user: root

  tasks:
  - name: Ensure necessary packages are present
    apt:
      update_cache: true
      name:
        - git
        - maven
      state: present

  - name: Clone boxfuse repo
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /src/boxfuse-sample-java-war-hello

  - name: Build boxfuse using maven
    shell:
      chdir: /src/boxfuse-sample-java-war-hello/
      executable: /bin/bash
      cmd: mvn package
      creates: /src/boxfuse-sample-java-war-hello/target/hello-1.0.war

  - name: Fetch built WAR from build host
    fetch:
      src: /src/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /tmp/
      flat: yes

- name: Launch boxfuse app in tomcat
  hosts: prod
  become: yes
  become_user: root

  tasks:
  - name: Ensure tomcat pkg is present
    apt:
      name: tomcat9
      state: present

  - name: Copy built WAR to app host
    copy:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/

  - name: Ensure tomcat is up and running
    service:
      name: tomcat9
      state: started
